name: UNITY

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Builder
        uses: game-ci/unity-builder@v4.1.1
        with:
          projectPath: ./
