name: UNITY

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Request Activation File
        uses: game-ci/unity-request-activation-file@v2.0.0
      - name: Unity - Builder
        uses: game-ci/unity-builder@v4.1.1
